spring.application.name=web

# Spring usará la variable de entorno o, si no existe, usará lo que esté después de los dos puntos (:)
spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:repositorio_web}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:12345678}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Tamaño máximo por archivo
spring.servlet.multipart.max-file-size=50MB

# Tamaño máximo total por request
spring.servlet.multipart.max-request-size=50MB

file.upload-dir=uploads